config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  root to: 'pages#home'

  devise_for :users

  resource :cart, only: [:show]

  resources :orders do
    resources :payments, only: [:new, :create]
  end
  resources :products do
    resources :order_lines
  end
  resources :bakers do
    resources :reviews
    get 'profile', to: 'bakers#profile', as: :profile
    patch 'order/:id' , to: 'bakers#close_order', as: :close_order
  end

end

app/models/baker.rb
class Baker < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  has_many :products, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

   def new_averagerate(rating)

     if self.averagerate.blank?
        self.averagerate =rating
        self.save
      else
        sum = 0
        self.reviews.each do |review|
          sum += review.rate
          p sum
        end
        self.averagerate = (sum.to_f / self.reviews.size.to_f)
        self.save
      end
   end

  def has_order?
    self.products.each do |product|
      return true if product.order_lines.nil?
    end
    return false
  end
end

app/controllers/bakers_controller.rb
class BakersController < ApplicationController
  before_action :set_baker, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :new]

  # GET /bakers
  # GET /bakers.json
  def profile
    @baker = Baker.find(params[:baker_id])
  end

  def index
    @bakers = Baker.all.reject{|baker| baker.products == [] }
     # Let's DYNAMICALLY build the markers for the view.
    if params[:autocomplete_search]
      @bakers = Baker.near(params[:autocomplete_search], 50)
       @bakers = @bakers.reject{|baker| baker.products == [] }
    end

    @markers = Gmaps4rails.build_markers(@bakers) do |baker, marker|
      marker.lat baker.latitude
      marker.lng baker.longitude
    end
  end

  # GET /bakers/1
  # GET /bakers/1.json
  def show
    @review = Review.new
  end

  # GET /bakers/new
  def new
    @baker = Baker.new
  end

  # GET /bakers/1/edit
  def edit
  end

  # POST /bakers
  # POST /bakers.json
  def create
    @baker = Baker.new(baker_params)

    respond_to do |format|
      if @baker.save
        format.html { redirect_to @baker, notice: 'Baker was successfully created.' }
        format.json { render :show, status: :created, location: @baker }
      else
        format.html { render :new }
        format.json { render json: @baker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bakers/1
  # PATCH/PUT /bakers/1.json
  #
  def close_order
    @order = Order.find(params[:id])
    @order.state = "CLOSED"
    @order.save
    redirect_to baker_profile_path(@order.baker)
  end

  def update
    respond_to do |format|
      if @baker.update(baker_params)
        format.html { redirect_to @baker, notice: 'Baker was successfully updated.' }
        format.json { render :show, status: :ok, location: @baker }
      else
        format.html { render :edit }
        format.json { render json: @baker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bakers/1
  # DELETE /bakers/1.json
  def destroy
    @baker.destroy
    respond_to do |format|
      format.html { redirect_to bakers_url, notice: 'Baker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baker
      @baker = Baker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baker_params
      params.require(:baker).permit(:firstname, :lastname, :description, :address, :photo, :photo_cache)
    end
  end

app/helpers/bakers_helper.rb
module BakersHelper
end

app/views/bakers/_form.html.erb
<!-- <div class="container">
        <div class="centered-form">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3"> -->
          <div class="panel panel-default">
            <div class="panel-heading" style="padding:30px 0 30px 0; text-align: center;">

              <h7>Update your profile</h7>

            </div>
            <div class="panel-body">
            <form role="form">
                <div class="row">

                <%= simple_form_for(@baker) do |f| %>
                <%= f.error_notification %>

                <div class="form-inputs">
                    <div class="col-xs-12 col-sm-6">
                    <div class="form-group">
                  <%= f.input :firstname, :placeholder => "First name",label_html: { class: 'sr-only' }%>
                  </div>
                  </div>
                      <div class="col-xs-12 col-sm-6">
                    <div class="form-group">
                  <%= f.input :lastname, :placeholder => "Last name", label_html: { class: 'sr-only' } %>
                  </div>
                  </div>
                  <div class="col-xs-12">
                    <div class="form-group">
                  <%= f.input :description,:as => :text, :placeholder => "Tell us about yourself...", :input_html => { 'rows' => 5 },  label_html: { class: 'sr-only' } %>
                  </div>
                  </div>
                    <div class="col-xs-12">
                    <div class="form-group">
                  <%= f.input :address, :placeholder => "Address",  label_html: { class: 'sr-only' }%>
                  </div>
                  </div>

                    <div class="col-xs-12">
                    <div class="form-group" >
                  <%= f.input :photo%>
                  <%= f.input :photo_cache, as: :hidden %>
                  </div>
                  </div>

                </div>
                  <div class="col-xs-12">
                    <div class="form-group">
                <div class="form-actions">
                  <%= f.button :submit %>
                </div>
                </div>
                </div>
                <% end %>
                </div>
                </div>
              </div>
            </div>
  <!--           </div>
            </div>
            </div> -->

app/views/bakers/_header.html.erb
<div class="nav" style="padding: 15px 0 5px 0">
   <ul class="list-inline text-center" style="font-size: 14px">

      <!--  <li><a href="#newform-anchor">Open shop</a></li> -->

       <li><a href="#pricing-anchor">Pricing</a></li>
       <li><a href="#questions-anchor">Frequently Asked Questions</a></li>
   </ul>
</div>

app/views/bakers/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @baker %> |
<%= link_to 'Back', bakers_path %>

app/views/bakers/index.html.erb
<h4 class="text-center">Your own personal baker is just next to you!</h4>

<div class='container text-center' id="map" style="width: 70%; height: 300px;"></div>

<div class="wrapper padded_bakers">
  <div class="container">

    <div class="row">

     <% @bakers.each do |baker| %>

      <div class="col-xs-12 col-sm-4">

        <div class="card card-container" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path baker.products.first.photo %>');">
          <a class="card-link" href="bakers/<%= baker.id %>"></a>

          <div class="card-category"> <%= image_tag baker.photo, class: "avatar-large" %> <%= baker.firstname %> <%= baker.lastname %>
          </div>
          <div class="card-description">
          <h2><%= baker.products.first.name %></h2>
          </div>
        </div>
      </div>
    <% end %>

    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

  <%= javascript_tag do %>
  $(document).on('ready', function() {

  handler = Gmaps.build('Google');
  handler.buildMap({ internal: { id: 'map' } }, function(){
  markers = handler.addMarkers(<%= raw @markers.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });
  })
  <% end %>
<% end %>

app/views/bakers/profile.html.erb
 <div class="profile-header-wrapper">
      <div class="container profile-header-container text-center">
        <div class="profile-header-infos">
          <%= image_tag @baker.photo, class: "round" %>
          <h4 style="color:wheat;"><%= @baker.firstname %> <%= @baker.lastname %></h4>

        <p style="color: white;">
          <%= @baker.address %>
        </p>
         <p style="color: white;">
       <!--    <strong>Average Rate:</strong> -->
          <% if @baker.averagerate.blank?%>
            <h5><%= @baker.firstname%> doesn't have rates yet. </h5>
          <% else %>
          <div class="star-ratings-sprite"><span style="width:<%= (@baker.averagerate * 20).to_i if @baker.averagerate %>%" class="star-ratings-sprite-rating"></span></div>
          <%= '%.2f' %  @baker.averagerate %>
          <% end %>
        </p>
        </div>
        <div class="tabs">
          <a class="tab active" data-target="#bio">
            <h5>Profile</h5>
          </a>
          <a class="tab" data-target="#projects">
            <h5>Orders</h5>
          </a>
          <a class="tab" data-target="#contact">
            <h5>Reviews</h5>
          </a>
        </div>
      </div>
    </div>


    <div class=" tab-content box-general" id="bio">
        <div class="bakercard hovercard" style="margin: 20px 20px 0 20px">
          <div class="bakercardheader" style="padding:20px 0 20px 0">
            <p id="notice"><%= notice %></p>

            <h7>
              <%= @baker.firstname %> <%= @baker.lastname %>
            </h7>

            <p style="padding: 20px 0 20px 0">
              <%= image_tag @baker.photo %>
            </p>

            <p>
              <strong>About me:</strong>
              <%= @baker.description %>
            </p>

            <p>
              <strong>Address:</strong>
              <%= @baker.address %>
            </p>

            <p>
              <strong>Average Rate:</strong>
              <% if @baker.averagerate.blank?%>
                <h5><%= @baker.firstname%> doesn't have rates yet. </h5>
              <% else %>
              <div class="star-ratings-sprite"><span style="width:<%= (@baker.averagerate * 20).to_i if @baker.averagerate %>%" class="star-ratings-sprite-rating"></span></div>
              <%= '%.2f' %  @baker.averagerate %>
              <% end %>
            </p>

            <div class="bottom">
              <a class="btn btn-primary btn-twitter btn-sm" href="https://twitter.com/sweetjoy">
                <i class="fa fa-twitter"></i>
              </a>
              <a class="btn btn-danger btn-sm" rel="publisher"
              href="https://plus.google.com/+sweetjoy">
                <i class="fa fa-google-plus"></i>
              </a>
              <a class="btn btn-primary btn-sm" rel="publisher"
              href="https://plus.google.com/sweetjoy">
                <i class="fa fa-facebook"></i>
              </a>

            </div>

          </div>
        </div>


        <div class="box-item2" style="margin: 20px;">

          <%= render 'form' %>

          <%= link_to 'Show', @baker %>
        </div>
      </div>


<div class="tab-content hidden" id="projects">
  <div class="container">
    <div class="media-aside">
    <div class="media-section">
      <h7>Your Orders</h7>
          <div class="panel-body">
        <% if @baker.orders.present? %>
          <% @baker.orders.each do |order| %>
            <div>
              <hr class="style-four">
              <h2> Order n. <%= order.id %>: </h2>
              <% order.order_lines.each do |order_line| %>
                <div>
                  <h6> - Product: <%= order_line.product.name %></h6>
                  <h6> - Special Instructions: <%= order_line.special_instruction %></h6>
                </div>
                <hr class="style-one">
              <% end %>
              <h5>Address: <%= order.delivery_address %></h5>
              <h5>Date: <%= order.delivery_date %></h5>
              <h5>Status: <%= order.state %>
                <% if order.state == 'PAID' %>
                  <%= link_to "Change to Delivered", baker_close_order_path(@baker, order), method: 'patch', class: "btn btn-default" %>
                <% end %>
              </h5>
              <hr class="style-four">
            </div>
          <% end %>
        <% else %>
          <p>You don't have any order yet.</p>
        <% end %>
    </div>
    </div>
  </div>
</div>
      </div>


      <div class="tab-content hidden" id="contact">
      <div class="container" style="padding-bottom: 50px">
<div class="media-aside">
    <div class="media-section">

  <h7>Your Reviews</h7>
        <div class="panel-body">
       <% if @baker.reviews.blank? %>
        <h5>You don't have reviews yet.</h5>
       <% else %>
        <% @baker.reviews.each do |review| %>
          <p><%= image_tag 'nophoto.png', class: 'avatar-large'%></p>
          <p><%=review.content%></p>
          <div class="star-ratings-sprite-review"><span style="width:<%= (review.rate * 20).to_i %>%" class="star-ratings-sprite-rating"></span></div>
        <% end %>
       <% end %>
     </div>
      </div>
      </div>
      </div>
      </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="javascript/tabs.js"></script>

app/views/bakers/show.html.erb
 <div class="profile-header-wrapper">
      <div class="container profile-header-container text-center">
        <div class="profile-header-infos">
          <%= image_tag @baker.photo, class: "round" %>
          <h4 style="color:wheat;"><%= @baker.firstname %> <%= @baker.lastname %></h4>

        <p style="color: white;">
          <%= @baker.address %>
        </p>
         <p>
       <!--    <strong>Average Rate:</strong> -->
          <% if @baker.averagerate.blank?%>
            <h5><%= @baker.firstname%> doesn't have rates yet. </h5>
          <% else %>
          <div class="star-ratings-sprite"><span style="width:<%= (@baker.averagerate * 20).to_i if @baker.averagerate %>%" class="star-ratings-sprite-rating"></span></div>
          <div class="average-rate"><%= '%.2f' %  @baker.averagerate %></div>
          <% end %>
        </p>
        </div>
        <div class="tabs">
          <a class="tab active" href='#bio' data-target="#bio">
            <h5>About me</h5>
          </a>
          <a class="tab" data-target="#projects" href="#projects">
            <h5>Shop</h5>
          </a>
          <a class="tab" data-target="#contact" href="#contact">
            <h5>Reviews</h5>
          </a>
        </div>
      </div>
    </div>




      <div class="tab-content" id="bio">

    <div class="bakercard hovercard" style="margin: 0 20px 20px 20px">
      <div class="bakercardheader">

        <p style="padding: 20px 0 20px 0">
            <h7>
              <%= @baker.firstname %> <%= @baker.lastname %>
            </h7>
            </p>

            <p style="padding: 20px 0 20px 0">
              <%= image_tag @baker.photo %>
            </p>

            <p>
              <strong>About me:</strong>
              <%= @baker.description %>
            </p>

            <p>
              <strong>Address:</strong>
              <%= @baker.address %>
            </p>

            <p>
              <strong>Average Rate:</strong>
              <% if @baker.averagerate.blank?%>
                <h5><%= @baker.firstname%> doesn't have rates yet. </h5>
              <% else %>
              <div class="star-ratings-sprite"><span style="width:<%= (@baker.averagerate * 20).to_i if @baker.averagerate %>%" class="star-ratings-sprite-rating"></span></div>
              <%= '%.2f' %  @baker.averagerate %>
              <% end %>
            </p>

            <div class="bottom">
              <a class="btn btn-primary btn-twitter btn-sm" href="https://twitter.com/sweetjoy">
                <i class="fa fa-twitter"></i>
              </a>
              <a class="btn btn-danger btn-sm" rel="publisher"
              href="https://plus.google.com/+sweetjoy">
                <i class="fa fa-google-plus"></i>
              </a>
              <a class="btn btn-primary btn-sm" rel="publisher"
              href="https://plus.google.com/sweetjoy">
                <i class="fa fa-facebook"></i>
              </a>

            </div>

          </div>
        </div>


  </div>


      <div class="tab-content hidden" id="projects">
       <div class="container">

  <div class="row text-center" style="padding-bottom: 40px;">
    <h7>See <%=@baker.firstname%>'s collection</h7>
    </div>

    <% @baker.products.each do |product| %>
    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 column productbox">

      <%= image_tag product.photo, class: "img-responsive" %>

     <div class="producttitle"><%= product.name %></div>
     <div class="productdescription"><%= product.description %></div>
     <div class="productprice">
     <div class="pull-right">
      <% if current_user %>
        <%= link_to "Order", product_path(product), class: "btn btn-default"%>
      <% else %>
        <%= link_to "Log in to Buy", new_user_session_path, class: "btn btn-default"%>
      <% end %>
      </div>
      <div class="pricetext">R$<%= product.price %></div>
    </div>

    </div>
    <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
         <%= render 'order_lines/form', product: product, order_line:OrderLine.new %>
       </div>
     </div>
   </div>
  <% end%>
  </div>
</div>
      </div>


      <div class="tab-content hidden" id="contact">
      <div class="container" style="padding-bottom: 50px">

  <h7>Reviews</h7>
  <!-- Iterating to check if the user has a order to this baker -->
  <% has_order = false %>
  <% @baker.products.each do |product| %>
    <% product.order_lines.each do |order_line| %>
      <% has_order = true  if order_line.order.user == current_user %>
    <%end%>
  <%end%>
  <!-- If the user has a order to this baker he can add a review otherwise just see the reviews -->
  <% if has_order %>
    <% if @baker.reviews.blank? %>
      <p>Be the first to leave a review for <%= @baker.firstname %></p>
    <% else %>
      <% @baker.reviews.each do |review| %>
        <p><%= image_tag 'nophoto.png', class: 'avatar-large'%></p>
        <p><%=review.content%></p>
        <div class="star-ratings-sprite" style="margin:0;"><span style="width:<%= (review.rate * 20).to_i %>%" class="star-ratings-sprite-rating"></span></div>
      <% end %>
    <% end %>

    <div class="padded">
    <button type="button padded" class="btn btn-primary" data-toggle="modal" data-target=".bs-add-order-details">Add a new review</button>
    </div>
  <% else %>
    <% if @baker.reviews.blank? %>
      <h5><%= @baker.firstname %> doesn't have reviews yet</h5>
    <% else %>
      <% @baker.reviews.each do |review| %>
          <p><%= image_tag 'nophoto.png', class: 'avatar-large'%></p>
          <p><%=review.content%></p>
          <div class="star-ratings-sprite-review">
          <span style="width:<%= (review.rate * 20).to_i %>%" class="star-ratings-sprite-rating"></span></div>
      <% end %>
    <% end %>
  <% end %>

  <div class="modal fade bs-add-order-details" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-body"> <%= render 'reviews/form', baker: @baker, review: @review %> </div>
      </div>
    </div>
  </div>
      </div>
      </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="javascript/tabs.js"></script>