config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  root to: 'pages#home'

  devise_for :users

  resource :cart, only: [:show]

  resources :orders do
    resources :payments, only: [:new, :create]
  end
  resources :products do
    resources :order_lines
  end
  resources :bakers do
    resources :reviews
    get 'profile', to: 'bakers#profile', as: :profile
    patch 'order/:id' , to: 'bakers#close_order', as: :close_order
  end

end

app/models/baker.rb
class Baker < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  has_many :products, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

   def new_averagerate(rating)

     if self.averagerate.blank?
        self.averagerate =rating
        self.save
      else
        sum = 0
        self.reviews.each do |review|
          sum += review.rate
          p sum
        end
        self.averagerate = (sum.to_f / self.reviews.size.to_f)
        self.save
      end
   end

  def has_order?
    self.products.each do |product|
      return true if product.order_lines.nil?
    end
    return false
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :baker
  has_many :order_lines, dependent: :destroy
  monetize :amount_cents


  def is_open?
    state == 'OPEN'
  end

  def total
    total =0
    self.order_lines.each {|ol| total += ol.quantity * ol.product.price.to_i }
    total * 100
  end
end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  validates :quantity, presence: true

  def amount
    self.product.price_cents * self.quantity
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  belongs_to :baker
  has_many :order_lines, dependent: :destroy
  monetize :price_cents
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :baker
  belongs_to :user

  validates :content, length: { minimum: 20 }
  validates :rate, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :baker, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/bakers_controller.rb
class BakersController < ApplicationController
  before_action :set_baker, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :new]

  # GET /bakers
  # GET /bakers.json
  def profile
    @baker = Baker.find(params[:baker_id])
  end

  def index
    @bakers = Baker.all.reject{|baker| baker.products == [] }
     # Let's DYNAMICALLY build the markers for the view.
    if params[:autocomplete_search]
      @bakers = Baker.near(params[:autocomplete_search], 50)
       @bakers = @bakers.reject{|baker| baker.products == [] }
    end

    @markers = Gmaps4rails.build_markers(@bakers) do |baker, marker|
      marker.lat baker.latitude
      marker.lng baker.longitude
    end
  end

  # GET /bakers/1
  # GET /bakers/1.json
  def show
    @review = Review.new
  end

  # GET /bakers/new
  def new
    @baker = Baker.new
  end

  # GET /bakers/1/edit
  def edit
  end

  # POST /bakers
  # POST /bakers.json
  def create
    @baker = Baker.new(baker_params)

    respond_to do |format|
      if @baker.save
        format.html { redirect_to @baker, notice: 'Baker was successfully created.' }
        format.json { render :show, status: :created, location: @baker }
      else
        format.html { render :new }
        format.json { render json: @baker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bakers/1
  # PATCH/PUT /bakers/1.json
  #
  def close_order
    @order = Order.find(params[:id])
    @order.state = "CLOSED"
    @order.save
    redirect_to baker_profile_path(@order.baker)
  end

  def update
    respond_to do |format|
      if @baker.update(baker_params)
        format.html { redirect_to @baker, notice: 'Baker was successfully updated.' }
        format.json { render :show, status: :ok, location: @baker }
      else
        format.html { render :edit }
        format.json { render json: @baker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bakers/1
  # DELETE /bakers/1.json
  def destroy
    @baker.destroy
    respond_to do |format|
      format.html { redirect_to bakers_url, notice: 'Baker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baker
      @baker = Baker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baker_params
      params.require(:baker).permit(:firstname, :lastname, :description, :address, :photo, :photo_cache)
    end
  end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = current_user.orders.where(state: "OPEN").last

    unless @order
      flash[:alert] = "Your cart is empty"
      redirect_to root_path
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  def checkout
    @order = Order.find(params[:order_id])
  end
  # GET /orders/1
  # GET /orders/1.json
  def show
    # @product = Product.find(params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = current_user.order.new(order_pcreation_arams)

    if @order.save
      redirect_to @order, notice: 'Order was successfully created.'
    else
     render :new
    end
 end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    if @order.update(order_update_params)
      redirect_to new_order_payment_path(@order)
    else
      flash[:alert] = "Unable to proceed to checkout"
      render :show
    end


    # respond_to do |format|
    #   if @order.update(status: "PAID")
    #     format.html { redirect_to @order, notice: 'Order was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @order }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @order.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_creation_params
    params.require(:order).permit(:delivery_address, :delivery_date)
  end

  def order_update_params
    params.require(:order).permit(
      :fullname,
      :delivery_address,
      :delivery_date,
      :instructions
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @bakers = Baker.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bakers_helper.rb
module BakersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/orders_lines_helper.rb
module OrdersLinesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag 'logo.png' %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url(meta_image) %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    <meta itemprop="image" content="<%= image_url(meta_image) %>">

  </head>
  <body class='<%= "#{params[:controller]}-#{params[:action]}" %>'>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/footer' %>

    <%= javascript_include_tag "application" %>


    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>

    <%= yield(:after_js) %>


  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="content">
    <p><h3 style="text-shadow: 0px 2px 1px rgba(0, 0, 0, 0.17)";>Discover sweet creations around you...</h3></p>
    <!-- Search form -->
    <form action="bakers" class="text-center">
      <input type="text" id='autocomplete-search' name='autocomplete_search' class="navbar-wagon-search-input" placeholder="Enter a full address">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search fa-2x"></i>
      </button>
    </form>
  </div>
</div>

<!-- how it works section -->

<div id="trust" class="padded">

  <div class="container text-center padded features">
  <!--  <div class="row"> -->
     <div class="col-xs-12 col-sm-6 col-md-3">
      <h2>How it works</h2>
      <p style="margin-bottom: 25px;">We source the freshest and best tasting cakes from home bakers around the world</p>
        <%= link_to "Get started", products_path, class: 'btn-medium' %>

    </div>
    <div class="col-xs-12 col-sm-6 col-md-3">
     <!-- <img src="images/globe.png" alt=""> -->
     <i class="fa fa-search fa-4x" id="large-icon"></i>
     <h2>1.</h2>
     <p>Select your cake</p>
   </div>
   <div class="col-xs-12 col-sm-6 col-md-3">
     <!-- <img src="images/dollar.png" alt=""> -->
     <i class="fa fa-mouse-pointer fa-4x"></i>

     <h2>2.</h2>
     <p>Place an order</p>
   </div>
   <div class="col-xs-12 col-sm-6 col-md-3">
     <!-- <img src="images/beer.png" alt=""> -->
     <i class="fa fa-birthday-cake fa-4x"></i>

     <h2>3.</h2>
     <p>Pick up your cake and enjoy!</p>
   </div>
 </div>
</div>


<div class="blue-background">
<div class="wrapper padded_bakers">
  <div class="container">

<!--     <div class="row"> -->
<div class="row text-center" style="padding-bottom: 40px;">
    <h7>Top bakers</h7>
    </div>
     <% @bakers.sample(3).each do |baker| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path baker.products.first.photo%>');">
          <a class="card-link" href="bakers/<%= baker.id %>"></a>
          <div class="card-category"> <%= image_tag baker.photo, class: "avatar-large" %> <%= baker.firstname %> <%= baker.lastname %>
          </div>
          <div class="card-description">
            <h2><%= baker.products.first.name %></h2>
          </div>
        </div>
      </div>




    <% end %>

  </div>
</div>
</div>

<div class="cardhow">
 <div class="text-center padded">
   <h7>Meet Joicy</h7>
 </div>
</div>
<div class="bannernew">
</div>



<div id="trust">
  <div class="content">
    <div class="container text-center padded features">

      <!--  <div class="card-user avatar"> -->


      <div class="cardhow padded">

        <p><i><strong>I think baking is a labour of love, passed down from generation to generation.</strong></i></p>
        <p>Meet <%=link_to "Joicy", baker_path(id="1") %> from Curitiba, Brazil</p>
      </div>

  </div>
</div>
</div>

<% content_for :after_js do %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <script type="text/javascript">
    function initializeAutocomplete(id) {
      var element = document.getElementById(id);
      console.log(element)
      if (element) {
        var autocomplete = new google.maps.places.Autocomplete(element, { types: ['geocode'] });
        google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
      }
    }

    function onPlaceChanged() {
      var place = this.getPlace();

      // console.log(place);  // Uncomment this line to view the full object returned by Google API.

      for (var i in place.address_components) {
        var component = place.address_components[i];
        for (var j in component.types) {  // Some types are ["country", "political"]
          var type_element = document.getElementById(component.types[j]);
          if (type_element) {
            type_element.value = component.long_name;
          }
        }
      }
    }

    google.maps.event.addDomListener(window, 'load', function() {

    console.log('works')
      initializeAutocomplete('autocomplete-search');
    });
  </script>

<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer" class="text-center padded">
    <ul class="list-inline">
    <li>
      <a href="https://www.youtube.com/watch?v=e0HKFx7zJKw">
        <i class="fa fa-youtube fa-3x" style="color: white"></i>
      </a>
    </li>
    <li>
      <a href="https://www.instagram.com/p/-1ZQKqooyd/">
        <i class="fa fa-instagram fa-3x" style="color: white"></i>
      </a>
    </li>
    <li>
      <a href="https://www.facebook.com/Sweet-Joy-Cafe-e-Confeitaria-290633780988236/?fref=ts">
        <i class="fa fa-facebook fa-3x" style="color: white"></i>
      </a>
    </li>
    <li>
      <a href="https://twitter.com/SweetJoy_BR">
        <i class="fa fa-twitter fa-3x" style="color: white"></i>
      </a>
    </li>
    </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag params[:action] == 'home' ? "white-logo.png" : "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.baker.blank? %>
            <% user_image = 'nophoto.png' %>
          <% else %>
            <% user_image = current_user.baker.photo %>
          <% end %>

          <%= image_tag user_image, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% if current_user.baker %>
            <li>
              <%= link_to baker_profile_path(current_user.baker) do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Baker Profile" %>
              <% end %>
            </li>
            <% end %>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "btn btn-default" %>

    <% end %>

    <!-- Button (call-to-action) -->

    <% if user_signed_in? %>

      <% if current_user.baker.blank? %>
        <%= link_to t(".top_call_to_action", default: "Become a Baker"), new_baker_path, class: "btn btn-default" %>
      <% end %>
      <% if current_user.orders.present? %>
        <%= link_to t(".top_call_to_action", default: ""), order_path(current_user.orders.last), class: "glyphicon glyphicon-shopping-cart fa-2x" %>
      <% end %>
    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>hover
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>