config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  root to: 'pages#home'

  devise_for :users

  resource :cart, only: [:show]

  resources :orders do
    resources :payments, only: [:new, :create]
  end
  resources :products do
    resources :order_lines
  end
  resources :bakers do
    resources :reviews
    get 'profile', to: 'bakers#profile', as: :profile
    patch 'order/:id' , to: 'bakers#close_order', as: :close_order
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  belongs_to :baker
  has_many :order_lines, dependent: :destroy
  monetize :price_cents
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  # GET /products
  # GET /products.json

  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :baker_id, :photo, :photo_cache)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.association :baker %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="media-section media-aside text-center">

<h7 class="text-center" style="padding-top: 80px">Browse our cakes</h7>
<div class='container'>


<div class="hidden">
<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Baker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.baker.firstname %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>
</div>

</div>

</div>

<div class="container">
<div class="card-columns">
<% @products.each do |product| %>
<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 column productbox">

   <%= image_tag product.photo, class: "img-responsive" %>

    <div class="producttitle"><%= product.name %></div>
    <div class="producttitle2" id="grey">by <%= product.baker.firstname %></div>

    <div class="productdescription"><%= product.description %></div>
    <div class="productprice" style="display: flex; align-items: center">
      <div class="pull-right">
      <% if current_user %>
        <%= link_to "Order", product_path(product), class: "btn btn-default"%>
      <% else %>
        <%= link_to "Log in to Buy", new_user_session_path, class: "btn btn-default"%>
      <% end %>
      </div>
      <div class="pricetext">R$<%= product.price %></div>
    </div>

</div>
<% end%>
</div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class='productcard-container'>
  <div class='productcard'>
    <div class='productcard-photo'>
      <%= image_tag @product.photo.url, width: '100%' %>
      <div class='productcard-price'>
        <span style="background: #469AE0;
    display: inline-block;
    padding: 11px;
    font-size: 18px;
  /*  border-radius: 0 4px 4px 0;*/
    box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.49);"><%= @product.price %> R$</span>
      </div>
    </div>

    <div class='productcard-name'>
      <%= @product.name %>
    </div>

    <div class='productcard-description'>
      <%= @product.description %>
    </div>


    <div class="productcard-author">
      by <%= @product.baker.firstname %>
    </div>



 <!--    <a class="cart-button" rel="nofollow" data-method="post" href="/products/4/orders">Add to Cart</a> -->

    <%= button_to 'Add to Cart', product_order_lines_path(@product, OrderLine.new), method: 'post', class:"cart-button" %>


    </div>
    </div>




<div class="modal fade bs-add-order-details" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <%= render 'order_lines/form', product: @product, order_line:OrderLine.new %>
      </div>
    </div>
  </div>
</div>